apps/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import ProductListView, ProductDetailTemplateView, RegisterCreateView, \
    SettingsUpdateView, FavouriteView, CartListView, CartItemDeleteView, AddToCartView, CustomLogoutView, \
    CheckoutListView, \
    AddressCreateView, AddressUpdateView, OrderCreateView, OrderListView, OrderDetailView, OrderDeleteView, \
    OrderPdfCreateView

urlpatterns = [
    # path('rv/', ProductLIstTemplateView.as_view(), name='product_list'),
    path('', ProductListView.as_view(), name='product_list_page'),
    path('product-detail/<int:pk>/', ProductDetailTemplateView.as_view(), name='product_detail'),

    path('settings', SettingsUpdateView.as_view(), name='settings_page'),
    path('register', RegisterCreateView.as_view(), name='register_page'),

    path('login', LoginView.as_view(
        template_name='apps/auth/login.html',
        redirect_authenticated_user=True
    ), name='login_page'),
    path('logout', CustomLogoutView.as_view(template_name='apps/auth/login.html'), name='logout_page'),

    path('shopping-cart', CartListView.as_view(), name='shopping_cart_page'),
    path('remove-cart/<int:pk>/', CartItemDeleteView.as_view(), name='delete_cart_item'),
    path('add-to-cart/<int:pk>/', AddToCartView.as_view(), name='add_cart_page'),

    path('favorite/<int:pk>', FavouriteView.as_view(), name='add_favorite'),

    path('checkout', CheckoutListView.as_view(), name='checkout_page'),

    path('addres-create', AddressCreateView.as_view(), name='create_address'),
    path('address-update/<int:pk>/', AddressUpdateView.as_view(), name='update_address'),

    path('orders', OrderListView.as_view(), name='orders_list'),
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order'),
    path('order/delete/<int:pk>', OrderDeleteView.as_view(), name='order_delete'),
    path('download-pdf/<int:pk>', OrderPdfCreateView.as_view(), name='download_pdf'),


]

root/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from root.settings import MEDIA_URL, MEDIA_ROOT, STATIC_URL, STATIC_ROOT

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include('apps.urls')),
                  path("ckeditor5/", include('django_ckeditor_5.urls')),
                  path('accounts/', include('allauth.urls')),
              ] + debug_toolbar_urls() + static(MEDIA_URL, document_root=MEDIA_ROOT) + static(STATIC_URL,
                                                                                              document_root=STATIC_ROOT)

apps/models.py
from datetime import timedelta
from decimal import Decimal

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser
from django.db.models import Model, JSONField, TextChoices, DateField, CharField, CASCADE, \
    PositiveIntegerField, ForeignKey, DateTimeField, TextField, EmailField, SlugField, ManyToManyField, DecimalField, \
    ImageField, BooleanField, Sum, F, FileField
from django.utils.text import slugify
from django.utils.timezone import now
from django_ckeditor_5.fields import CKEditor5Field
from mptt.models import MPTTModel, TreeForeignKey


# class CreatedBaseModel(Model):
#     updated_at = DateTimeField(auto_now=True)
#     created_at = DateTimeField(auto_now_add=True)
#
#     class Meta:
#         abstract = True


class User(AbstractUser):
    has_premium = BooleanField(default=False)

    @property
    def cart_count(self):
        return self.cart_items.count()


class Category(MPTTModel):
    name = CharField(max_length=255, unique=True)
    slug = SlugField(max_length=255, unique=True, editable=False)
    parent = TreeForeignKey('self', on_delete=CASCADE, null=True, blank=True, related_name='children')

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.slug:
            self.slug = slugify(self.name)
            unique = self.slug
            num = 1
            while Category.objects.filter(slug=unique).exists(): # todo Category orniga self qilib qoysak ozini olib ketadi
                unique = f'{self.slug}-{num}'
                num += 1
            self.slug = unique
        super().save(force_insert, force_update, using, update_fields)

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return self.name


class Product(Model):
    title = CharField(max_length=355)
    price = DecimalField(max_digits=7, decimal_places=2)
    price_percentage = DecimalField(max_digits=5, decimal_places=2, default=0)
    shopping_cost = DecimalField(default=0, max_digits=7, decimal_places=2)
    quantity = PositiveIntegerField(default=0)
    description = JSONField()
    short_description = CKEditor5Field()
    long_description = CKEditor5Field()
    category = ForeignKey('apps.Category', CASCADE)
    tags = ManyToManyField('apps.Tag', related_name='tag')
    updated_at = DateTimeField(auto_now_add=True)
    created_at = DateTimeField(auto_now_add=True)
    is_premium = BooleanField(default=False)

    def __str__(self):
        return self.title

    @property
    def new_price(self):
        return self.price * (100 - self.price_percentage) // 100

    @property
    def is_new(self) -> bool:
        return self.created_at >= now() - timedelta(days=7)

    @property
    def sub_amount(self):
        return self.price * self.quantity


class ImageProduct(Model):
    image = ImageField(upload_to='products/%Y/%m/%d/')
    product = ForeignKey('apps.Product', CASCADE, related_name='images')


class Tag(Model):
    name = CharField(max_length=255)
    slug = SlugField(max_length=255, unique=True, editable=False)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.slug:
            self.slug = slugify(self.name)
            unique = self.slug
            num = 1
            while Tag.objects.filter(slug=unique).exists():
                unique = f'{self.slug}-{num}'
                num += 1
            self.slug = unique
        super().save(force_insert, force_update, using, update_fields)


class Review(Model):
    name = CharField(max_length=255)
    email = EmailField(max_length=255, null=True, blank=True)
    description = TextField()
    comment_status = TextField()
    created_at = DateTimeField(auto_now_add=True)
    product = ForeignKey('apps.Product', CASCADE, related_name='reviw')

    def __str__(self):
        return self.name


class Favorite(Model):
    user = ForeignKey(User, CASCADE)
    product = ForeignKey('apps.Product', CASCADE)
    created_at = DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'product')


class CartItem(Model):
    product = ForeignKey('apps.Product', CASCADE)
    user = ForeignKey('apps.User', CASCADE, related_name='cart_items')
    quantity = PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.title}"

    @property
    def amount(self):
        return self.quantity * self.product.new_price

    @property
    def total(self):
        return self.amount - self.product.shopping_cost


class Order(Model):
    class StatusMethod(TextChoices):
        COMPLETED = 'completed', 'Completed'
        PROCESSING = 'processing', 'Processing'
        ON_HOLD = 'on hold', 'On Hold'
        PENDING = 'pending', 'Pending'

    class PaymentMethod(TextChoices):
        PAYPAL = 'paypal', 'Paypal'
        CREDIT_CARD = 'credit_card', 'Credit_card'

    status = CharField(max_length=255, choices=StatusMethod)
    payment_method = CharField(max_length=255, choices=PaymentMethod)
    address = ForeignKey('apps.Address', CASCADE)
    owner = ForeignKey('apps.User', CASCADE, related_name='orders')
    created_at = DateTimeField(auto_now_add=True)
    pdf_file = FileField(upload_to='order/pdf/', null=True, blank=True)

    def __str__(self):
        return f'Order {self.id} - {self.status}'

    @property
    def amount(self):
        aggregated = self.order_items.aggregate(
            subtotal=Sum(
                (F('quantity') * (F('product__price') * (100 - F('product__price_percentage')) / 100)) + F(
                    'product__shopping_cost')
            )
        )

        subtotal = aggregated['subtotal'] or Decimal('0')
        tax = subtotal * Decimal('0.10')
        total = subtotal + tax

        return {
            'subtotal': subtotal,
            'tax': tax,
            'total': total
        }


class OrderItem(Model):
    product = ForeignKey('apps.Product', CASCADE)
    order = ForeignKey('apps.Order', CASCADE, related_name='order_items')
    quantity = PositiveIntegerField(default=0)

    @property
    def sub_amount(self):
        return self.quantity * self.product.new_price


class Address(Model):
    user = ForeignKey('apps.User', CASCADE)
    full_name = CharField(max_length=255)
    street = CharField(max_length=255)
    zip_code = PositiveIntegerField()
    city = CharField(max_length=255)
    phone = CharField(max_length=255)


class CreditCard(Model):
    order = ForeignKey('apps.Order', CASCADE)
    number = CharField(max_length=255)
    cvv = CharField(max_length=255)
    expire_date = DateField()
    owner = ForeignKey('apps.User', CASCADE)


class SiteSettings(Model):
    tax = PositiveIntegerField()

    # @property
    # def sub_tax(self):
    #     return

    # TODO opshiy summadan tax di ovolish kerak nechi foiz bolsa foizda qilib
    # TODO pdf file di order ichiga saqlash kerak boladi pdf_field = order.pdf

templates/apps/product/product-details.html
{% extends 'apps/base.html' %}

{% load custom_tags %}

{% load static %}

{% block content %}
    <div class="card mb-3">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6 mb-4 mb-lg-0">
                    <div class="product-slider" id="galleryTop">
                        <div class="swiper-container theme-slider position-lg-absolute all-0"
                             data-swiper='{"autoHeight":true,"spaceBetween":5,"loop":true,"loopedSlides":5,"thumb":{"spaceBetween":5,"slidesPerView":5,"loop":true,"freeMode":true,"grabCursor":true,"loopedSlides":5,"centeredSlides":true,"slideToClickedSlide":true,"watchSlidesVisibility":true,"watchSlidesProgress":true,"parent":"#galleryTop"},"slideToClickedSlide":true}'>
                            <div class="swiper-wrapper h-100">
                                {% for p_image in product.images.all %}
                                    <div class="swiper-slide h-100">
                                        <a class="d-block h-sm-100"
                                           href="{% url 'product_detail' product.pk %}">
                                            <img
                                                    class="rounded-1 h-100 w-100 fit-cover"
                                                    src="{{ p_image.image.url }}" alt=""/>
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="swiper-nav">
                                <div class="swiper-button-next swiper-button-white"></div>
                                <div class="swiper-button-prev swiper-button-white"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <h5>{{ product.title }}</h5>
                    <a class="fs--1 mb-2 d-block"
                       href="{% url 'product_list_page' %}?category={{ product.category.slug }}">{{ product.category }}>
                        {{ product.category.name }}
                    </a>
                    <div class=" fs--2 mb-3 d-inline-block text-decoration-none"><span
                            class="fa fa-star text-warning"></span><span class="fa fa-star text-warning"></span><span
                            class="fa fa-star text-warning"></span><span class="fa fa-star text-warning"></span><span
                            class="fa fa-star-half-alt text-warning star-icon"></span><span
                            class="ms-1 text-600">(8)</span>
                    </div>
                    <p class="fs--1">
                        {{ product.short_description|safe }}
                    </p>
                    <h4 class="d-flex align-items-center"><span
                            class="text-warning me-2">${{ product.new_price }}</span><span
                            class="me-1 fs--1 text-500">
                    {% if product.price != product.new_price %}
                        <del class="me-1">${{ product.price }}</del><strong>-{{ product.price_percentage }}%</strong>
                        </span>
                        </h4>
                    {% endif %}
                    <p class="fs--1 mb-1"><span>Shipping Cost: </span><strong>${{ product.shopping_cost }}</strong></p>
                    {% if product.quantity == 0 %}
                        <p class="fs--1 mb-1">Stock: <strong
                                class="text-danger">Sold-Out</strong>
                        </p>
                    {% else %}
                        <p class="fs--1 mb-1">Stock: <strong
                            class="text-success">Available</strong>
                    {% endif %}

                    <p class="fs--1 mb-3">Tags:
                        {% for tag in product.tags.all %}
                            <a class="ms-1" href="{% url 'product_list_page' %}?tag={{ tag.slug }}">{{ tag.name }},</a>
                        {% endfor %}

                    </p>
                    <div class="row">
                        <div class="col-auto pe-0">
                            <div class="input-group input-group-sm" data-quantity="data-quantity">
                                <button class="btn btn-sm btn-outline-secondary border-300"
                                        data-field="input-quantity" data-type="minus">-
                                </button>
                                <input class="form-control text-center input-quantity input-spin-none"
                                       type="number" min="0" value="0"
                                       aria-label="Amount (to the nearest dollar)" style="max-width: 50px"/>
                                <button class="btn btn-sm btn-outline-secondary border-300"
                                        data-field="input-quantity" data-type="plus">+
                                </button>
                            </div>
                        </div>
                        <div class="col-auto px-2 px-md-3"><a class="btn btn-sm btn-primary"
                                                              href="{% url 'add_cart_page' product.pk %}"><span
                                class="fas fa-cart-plus me-sm-2"></span><span
                                class="d-none d-sm-inline-block">Add To Cart</span></a>
                        </div>
                        <div class="col-auto px-0">
                            <a class="btn btn-sm btn{% if not user|is_liked:product %}-outline{% endif %}-danger border-300"
                               href="{% url 'add_favorite' product.id %}"
                               data-bs-toggle="tooltip" data-bs-placement="top"
                               title="Add to Wish List">
                                <span class="far fa-heart me-1"></span>
                                {{ product.favorite_set.count }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="overflow-hidden mt-4">
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item"><a class="nav-link active ps-0" id="description-tab"
                                                    data-bs-toggle="tab" href="#tab-description" role="tab"
                                                    aria-controls="tab-description" aria-selected="true">Description</a>
                            </li>
                            <li class="nav-item"><a class="nav-link px-2 px-md-3" id="specifications-tab"
                                                    data-bs-toggle="tab" href="#tab-specifications" role="tab"
                                                    aria-controls="tab-specifications"
                                                    aria-selected="false">Specifications</a>
                            </li>
                            <li class="nav-item"><a class="nav-link px-2 px-md-3" id="reviews-tab"
                                                    data-bs-toggle="tab" href="#tab-reviews" role="tab"
                                                    aria-controls="tab-reviews"
                                                    aria-selected="false">Reviews</a></li>
                        </ul>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="tab-description" role="tabpanel"
                                 aria-labelledby="description-tab">
                                <div class="mt-3">
                                    <p>{{ product.long_description|safe }}</p>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="tab-specifications" role="tabpanel"
                                 aria-labelledby="specifications-tab">
                                <table class="table fs--1 mt-3">
                                    <tbody>
                                    {% for key, value in product.description.items %}
                                        <tr>
                                            <td class="bg-100" style="width: 30%;">{{ key }}</td>
                                            <td>{{ value }}</td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                            <div class="tab-pane fade" id="tab-reviews" role="tabpanel"
                                 aria-labelledby="reviews-tab">
                                <div class="row mt-3">

                                    {% for reviews in product.reviw.all %}
                                        <div class="col-lg-6 mb-4 mb-lg-0">
                                            <div class="mb-1"><span
                                                    class="fa fa-star text-warning fs--1"></span><span
                                                    class="fa fa-star text-warning fs--1"></span><span
                                                    class="fa fa-star text-warning fs--1"></span><span
                                                    class="fa fa-star text-warning fs--1"></span><span
                                                    class="fa fa-star text-warning fs--1"></span><span
                                                    class="ms-3 text-dark fw-semi-bold">{{ reviews.comment_status }}</span>
                                            </div>
                                            <p class="fs--1 mb-2 text-600">By {{ reviews.name }}
                                                • {{ reviews.created_at }}</p>
                                            <p class="mb-0">{{ reviews.description }}</p>
                                            <hr class="my-4"/>
                                        </div>
                                    {% endfor %}

                                    <div class="col-lg-6 ps-lg-5">
                                        <form>
                                            <h5 class="mb-3">Write your Review</h5>
                                            <div class="mb-3">
                                                <label class="form-label">Ratting: </label>
                                                <div class="d-block"
                                                     data-rater='{"starSize":32,"step":0.5}'></div>
                                            </div>
                                            <div class="mb-3">
                                                <label class="form-label" for="formGroupNameInput">Name:</label>
                                                <input class="form-control" id="formGroupNameInput"
                                                       type="text"/>
                                            </div>
                                            <div class="mb-3">
                                                <label class="form-label"
                                                       for="formGroupEmailInput">Email:</label>
                                                <input class="form-control" id="formGroupEmailInput"
                                                       type="email"/>
                                            </div>
                                            <div class="mb-3">
                                                <label class="form-label"
                                                       for="formGrouptextareaInput">Review:</label>
                                                <textarea class="form-control" id="formGrouptextareaInput"
                                                          rows="3"></textarea>
                                            </div>
                                            <button class="btn btn-primary" type="submit">Submit</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}