apps/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import ProductListView, ProductDetailTemplateView, RegisterCreateView, \
    SettingsUpdateView, FavouriteView, CartListView, CartItemDeleteView, AddToCartView, CustomLogoutView, \
    CheckoutListView, \
    AddressCreateView, AddressUpdateView, OrderCreateView, OrderListView, OrderDetailView, OrderDeleteView, \
    OrderPdfCreateView

urlpatterns = [
    # path('rv/', ProductLIstTemplateView.as_view(), name='product_list'),
    path('', ProductListView.as_view(), name='product_list_page'),
    path('product-detail/<int:pk>/', ProductDetailTemplateView.as_view(), name='product_detail'),

    path('settings', SettingsUpdateView.as_view(), name='settings_page'),
    path('register', RegisterCreateView.as_view(), name='register_page'),

    path('login', LoginView.as_view(
        template_name='apps/auth/login.html',
        redirect_authenticated_user=True
    ), name='login_page'),
    path('logout', CustomLogoutView.as_view(template_name='apps/auth/login.html'), name='logout_page'),

    path('shopping-cart', CartListView.as_view(), name='shopping_cart_page'),
    path('remove-cart/<int:pk>/', CartItemDeleteView.as_view(), name='delete_cart_item'),
    path('add-to-cart/<int:pk>/', AddToCartView.as_view(), name='add_cart_page'),

    path('favorite/<int:pk>', FavouriteView.as_view(), name='add_favorite'),

    path('checkout', CheckoutListView.as_view(), name='checkout_page'),

    path('addres-create', AddressCreateView.as_view(), name='create_address'),
    path('address-update/<int:pk>/', AddressUpdateView.as_view(), name='update_address'),

    path('orders', OrderListView.as_view(), name='orders_list'),
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order'),
    path('order/delete/<int:pk>', OrderDeleteView.as_view(), name='order_delete'),
    path('download-pdf/<int:pk>', OrderPdfCreateView.as_view(), name='download_pdf'),


]

root/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from root.settings import MEDIA_URL, MEDIA_ROOT, STATIC_URL, STATIC_ROOT

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include('apps.urls')),
                  path("ckeditor5/", include('django_ckeditor_5.urls')),
                  path('accounts/', include('allauth.urls')),
              ] + debug_toolbar_urls() + static(MEDIA_URL, document_root=MEDIA_ROOT) + static(STATIC_URL,
                                                                                              document_root=STATIC_ROOT)

apps/models.py
from datetime import timedelta
from decimal import Decimal

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser
from django.db.models import Model, JSONField, TextChoices, DateField, CharField, CASCADE, \
    PositiveIntegerField, ForeignKey, DateTimeField, TextField, EmailField, SlugField, ManyToManyField, DecimalField, \
    ImageField, BooleanField, Sum, F, FileField
from django.utils.text import slugify
from django.utils.timezone import now
from django_ckeditor_5.fields import CKEditor5Field
from mptt.models import MPTTModel, TreeForeignKey


# class CreatedBaseModel(Model):
#     updated_at = DateTimeField(auto_now=True)
#     created_at = DateTimeField(auto_now_add=True)
#
#     class Meta:
#         abstract = True


class User(AbstractUser):
    has_premium = BooleanField(default=False)

    @property
    def cart_count(self):
        return self.cart_items.count()


class Category(MPTTModel):
    name = CharField(max_length=255, unique=True)
    slug = SlugField(max_length=255, unique=True, editable=False)
    parent = TreeForeignKey('self', on_delete=CASCADE, null=True, blank=True, related_name='children')

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.slug:
            self.slug = slugify(self.name)
            unique = self.slug
            num = 1
            while Category.objects.filter(slug=unique).exists(): # todo Category orniga self qilib qoysak ozini olib ketadi
                unique = f'{self.slug}-{num}'
                num += 1
            self.slug = unique
        super().save(force_insert, force_update, using, update_fields)

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return self.name


class Product(Model):
    title = CharField(max_length=355)
    price = DecimalField(max_digits=7, decimal_places=2)
    price_percentage = DecimalField(max_digits=5, decimal_places=2, default=0)
    shopping_cost = DecimalField(default=0, max_digits=7, decimal_places=2)
    quantity = PositiveIntegerField(default=0)
    description = JSONField()
    short_description = CKEditor5Field()
    long_description = CKEditor5Field()
    category = ForeignKey('apps.Category', CASCADE)
    tags = ManyToManyField('apps.Tag', related_name='tag')
    updated_at = DateTimeField(auto_now_add=True)
    created_at = DateTimeField(auto_now_add=True)
    is_premium = BooleanField(default=False)

    def __str__(self):
        return self.title

    @property
    def new_price(self):
        return self.price * (100 - self.price_percentage) // 100

    @property
    def is_new(self) -> bool:
        return self.created_at >= now() - timedelta(days=7)

    @property
    def sub_amount(self):
        return self.price * self.quantity


class ImageProduct(Model):
    image = ImageField(upload_to='products/%Y/%m/%d/')
    product = ForeignKey('apps.Product', CASCADE, related_name='images')


class Tag(Model):
    name = CharField(max_length=255)
    slug = SlugField(max_length=255, unique=True, editable=False)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.slug:
            self.slug = slugify(self.name)
            unique = self.slug
            num = 1
            while Tag.objects.filter(slug=unique).exists():
                unique = f'{self.slug}-{num}'
                num += 1
            self.slug = unique
        super().save(force_insert, force_update, using, update_fields)


class Review(Model):
    name = CharField(max_length=255)
    email = EmailField(max_length=255, null=True, blank=True)
    description = TextField()
    comment_status = TextField()
    created_at = DateTimeField(auto_now_add=True)
    product = ForeignKey('apps.Product', CASCADE, related_name='reviw')

    def __str__(self):
        return self.name


class Favorite(Model):
    user = ForeignKey(User, CASCADE)
    product = ForeignKey('apps.Product', CASCADE)
    created_at = DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'product')


class CartItem(Model):
    product = ForeignKey('apps.Product', CASCADE)
    user = ForeignKey('apps.User', CASCADE, related_name='cart_items')
    quantity = PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.title}"

    @property
    def amount(self):
        return self.quantity * self.product.new_price

    @property
    def total(self):
        return self.amount - self.product.shopping_cost


class Order(Model):
    class StatusMethod(TextChoices):
        COMPLETED = 'completed', 'Completed'
        PROCESSING = 'processing', 'Processing'
        ON_HOLD = 'on hold', 'On Hold'
        PENDING = 'pending', 'Pending'

    class PaymentMethod(TextChoices):
        PAYPAL = 'paypal', 'Paypal'
        CREDIT_CARD = 'credit_card', 'Credit_card'

    status = CharField(max_length=255, choices=StatusMethod)
    payment_method = CharField(max_length=255, choices=PaymentMethod)
    address = ForeignKey('apps.Address', CASCADE)
    owner = ForeignKey('apps.User', CASCADE, related_name='orders')
    created_at = DateTimeField(auto_now_add=True)
    pdf_file = FileField(upload_to='order/pdf/', null=True, blank=True)

    def __str__(self):
        return f'Order {self.id} - {self.status}'

    @property
    def amount(self):
        aggregated = self.order_items.aggregate(
            subtotal=Sum(
                (F('quantity') * (F('product__price') * (100 - F('product__price_percentage')) / 100)) + F(
                    'product__shopping_cost')
            )
        )

        subtotal = aggregated['subtotal'] or Decimal('0')
        tax = subtotal * Decimal('0.10')
        total = subtotal + tax

        return {
            'subtotal': subtotal,
            'tax': tax,
            'total': total
        }


class OrderItem(Model):
    product = ForeignKey('apps.Product', CASCADE)
    order = ForeignKey('apps.Order', CASCADE, related_name='order_items')
    quantity = PositiveIntegerField(default=0)

    @property
    def sub_amount(self):
        return self.quantity * self.product.new_price


class Address(Model):
    user = ForeignKey('apps.User', CASCADE)
    full_name = CharField(max_length=255)
    street = CharField(max_length=255)
    zip_code = PositiveIntegerField()
    city = CharField(max_length=255)
    phone = CharField(max_length=255)


class CreditCard(Model):
    order = ForeignKey('apps.Order', CASCADE)
    number = CharField(max_length=255)
    cvv = CharField(max_length=255)
    expire_date = DateField()
    owner = ForeignKey('apps.User', CASCADE)


class SiteSettings(Model):
    tax = PositiveIntegerField()

    # @property
    # def sub_tax(self):
    #     return

    # TODO opshiy summadan tax di ovolish kerak nechi foiz bolsa foizda qilib
    # TODO pdf file di order ichiga saqlash kerak boladi pdf_field = order.pdf

templates/apps/shop/checkout.html
{% extends 'apps/base.html' %}

{% load static %}
{% load custom_tags %}
{% load humanize %}
{% block content %}



    <form method="post" action="{% url 'order_create' %}">
        {% csrf_token %}
        <div class="row g-3">
            <div class="col-xl-4 order-xl-1">
                <div class="card">
                    <div class="card-header bg-light btn-reveal-trigger d-flex flex-between-center">
                        <h5 class="mb-0">Order Summary</h5><a class="btn btn-link btn-sm btn-reveal text-600"
                                                              href="{% url 'shopping_cart_page' %}"><span
                            class="fas fa-pencil-alt"></span></a>
                    </div>

                    {% for cart_item in cart_items %}
                        <div class="card-body">
                        <table class="table table-borderless fs--1 mb-0">
                        <tr class="border-bottom">
                            <th class="ps-0 pt-0">{{ cart_item.product.title }} x {{ cart_item.quantity }}

                                <div class="text-400 fw-normal fs--2">
                                    {{ cart_item.product.short_description|safe }}
                                </div>
                            </th>

                            <th class="pe-0 text-end pt-0">${{ cart_item.amount|intcomma }}</th>
                        </tr>
                        <tr class="border-bottom">
                            <th class="ps-0">Subtotal</th>
                            <th class="pe-0 text-end">${{ cart_item.amount|intcomma }}</th>
                        </tr>
                    {% endfor %}

{#                    <tr class="border-bottom">#}
{#                        <th class="ps-0">Tax {{ tax }}</th>#}
{#                        <th class="pe-0 text-end">${{ sub_shipping_cost }}</th>#}
{#                    </tr>#}

                    <tr class="border-bottom">
                        <th class="ps-0">Shipping</th>
                        <th class="pe-0 text-end">${{ sub_shipping_cost }}</th>
                    </tr>

                    <tr>
                        <th class="ps-0 pb-0">Total</th>
                        <th class="pe-0 text-end pb-0">${{ all_total|intcomma }}</th>
                    </tr>


                    </table>
                    </div>
                    <div class="card-footer d-flex justify-content-between bg-light">
                        <div class="fw-semi-bold">Payable Total</div>
                        <div class="fw-bold">${{ all_total|intcomma }}</div>
                    </div>


                </div>
            </div>
            <div class="col-xl-8">
                <div class="card mb-3">
                    <div class="card-header bg-light">
                        <div class="card-header bg-light">
                            <div class="row flex-between-center">
                                <div class="col-sm-auto">
                                    <h5 class="mb-2 mb-sm-0">Your Shipping Address</h5>
                                </div>
                                <div class="col-sm-auto">
                                    <a class="btn btn-falcon-default btn-sm"
                                       href="{% url 'create_address' %}"><span
                                            class="fas fa-plus me-2" data-fa-transform="shrink-2"></span>Add New Address
                                    </a>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="card-body">
                        <div class="row">
                            {% for address in user.address_set.all %}
                                <div class="col-md-6 mb-3 mb-md-0">
                                    <div class="form-check mb-0 custom-radio radio-select">
                                        <input class="form-check-input" id="address-{{ address.pk }}" type="radio"
                                               name="address" checked="checked" value="{{ address.pk }}"/>
                                        <label class="form-check-label mb-0 fw-bold d-block"
                                               for="address-{{ address.pk }}">{{ address.full_name }}
                                            <span class="radio-select-content">
                                                <span>
                                                {{ address.city }}
                                                <br/>
                                                {{ address.street }}
                                                <br/>
                                                {{ address.zip_code }}
                                                <span class="d-block mb-0 pt-2">{{ address.phone|str_to_phone }}</span>
                                                </span>
                                            </span>
                                        </label>
                                        <a class="fs--1" href="{% url 'update_address' address.pk %}">Edit</a>
                                    </div>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header bg-light">
                        <h5 class="mb-0">Payment Method</h5>
                    </div>
                    <div class="card-body">
                        <div class="form-check mb-0">
                            <input class="form-check-input" type="radio" value="credit_card" id="credit-card"
                                   checked="checked" name="payment_method"/>
                            <label class="form-check-label mb-2 fs-1" for="credit-card">Credit Card</label>
                        </div>
                        <div class="row gx-0 ps-2 mb-4">
                            <div class="col-sm-8 px-3">
                                <div class="mb-3">
                                    <label class="form-label ls text-uppercase text-600 fw-semi-bold mb-0"
                                           for="inputNumber">Card Number</label>
                                    <input class="form-control" id="inputNumber" type="text"
                                           placeholder="•••• •••• •••• ••••" maxlength="16" minlength="16"
                                           name="number"/>
                                </div>
                                <div class="row align-items-center">
                                    <div class="col-6">
                                        <label class="form-label ls text-uppercase text-600 fw-semi-bold mb-0">Exp
                                            Date</label>
                                        <input class="form-control" type="text" placeholder="mm/yy" name="expire_date"
                                               id="expireDate"/>
                                    </div>
                                    <div class="col-6">
                                        <label class="form-label ls text-uppercase text-600 fw-semi-bold mb-0">CVV<a
                                                class="d-inline-block" href="#" data-bs-toggle="tooltip"
                                                data-bs-placement="top" title="Card verification value"><span
                                                class="fa fa-question-circle ms-2"></span></a></label>
                                        <input class="form-control" type="text" placeholder="123" minlength="3"
                                               maxlength="3" pattern="[0-9]{3}" name="cvv"/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-4 ps-3 text-center pt-2 d-none d-sm-block">
                                <div class="rounded-1 p-2 mt-3 bg-100">
                                    <div class="text-uppercase fs--2 fw-bold">We Accept</div>
                                    <img src="{% static 'apps/assets/img/icons/icon-payment-methods-grid.png' %}" alt=""
                                         width="120"/>
                                </div>
                            </div>
                        </div>
                        <div class="form-check d-flex align-items-center">
                            <input class="form-check-input" type="radio" value="paypal" id="paypal"
                                   name="payment_method"/>
                            <label class="form-check-label mb-0 ms-2" for="paypal"><img
                                    src="{% static 'apps/assets/img/icons/icon-paypal-full.png' %}" height="20" alt=""/></label>
                        </div>
                        <div class="border-dashed-bottom my-5"></div>
                        <div class="row">
                            <div class="col-md-7 col-xl-12 col-xxl-7 px-md-3 mb-xxl-0 position-relative">
                                <div class="d-flex"><img class="me-3"
                                                         src="{% static 'apps/assets/img/icons/shield.png' %}" alt=""
                                                         width="60" height="60"/>
                                    <div class="flex-1">
                                        <h5 class="mb-2">Buyer Protection</h5>
                                        <div class="form-check mb-0">
                                            <input class="form-check-input" id="protection-option-1" type="checkbox"
                                                   checked="checked"/>
                                            <label class="form-check-label mb-0" for="protection-option-1"> <strong>Full
                                                Refund </strong>If you don't <br class="d-none d-md-block d-lg-none"/>receive
                                                your order</label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" id="protection-option-2" type="checkbox"
                                                   checked="checked"/>
                                            <label class="form-check-label mb-0" for="protection-option-2"> <strong>Full
                                                or Partial Refund, </strong>If the product is not as described in
                                                details</label>
                                        </div>
                                        <a class="fs--1 ms-3 ps-2" href="#!">Learn More<span
                                                class="fas fa-caret-right ms-1" data-fa-transform="down-2"></span></a>
                                    </div>
                                </div>
                                <div class="vertical-line d-none d-md-block d-xl-none d-xxl-block"></div>
                            </div>
                            <div class="col-md-5 col-xl-12 col-xxl-5 ps-lg-4 ps-xl-2 ps-xxl-5 text-center text-md-start text-xl-center text-xxl-start">
                                <div class="border-dashed-bottom d-block d-md-none d-xl-block d-xxl-none my-4"></div>
                                <div class="fs-2 fw-semi-bold">All Total: <span
                                        class="text-primary">${{ all_total }}</span></div>
                                <button class="btn btn-success mt-3 px-5" type="submit">Confirm &amp; Pay</button>
                                <p class="fs--1 mt-3 mb-0">By clicking <strong>Confirm & Pay </strong>button you agree
                                    to the <a href="#!">Terms &amp; Conditions</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </form>
    <script>
        document.getElementById('orderForm').addEventListener('submit', function (event) {
            const expireDate = document.getElementById('expireDate').value;
            const [month, year] = expireDate.split('/').map(Number);

            // Convert the year to a full year (assuming 2000s)
            const fullYear = year + 2000;
            const now = new Date();
            const currentYear = now.getFullYear();
            const currentMonth = now.getMonth() + 1; // JavaScript months are 0-11, so we add 1

            // Create a date object for the expiration date (first day of the month)
            const expireDateObj = new Date(fullYear, month - 1, 1); // JavaScript months are 0-11, so we subtract 1

            if (month < 1 || month > 12) {
                alert('Invalid month. Please enter a valid expiration date.');
                event.preventDefault();
                return;
            }

            if (fullYear < currentYear || (fullYear === currentYear && month < currentMonth)) {
                alert('The card is expired.');
                event.preventDefault();
            }
        });
    </script>
{% endblock %}

templates/apps/shop/fovourit.html
{% extends 'apps/base.html' %}
{% load static %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <div class="row justify-content-between align-items-center">
                <div class="col-md-auto">
                    <h5 class="mb-3 mb-md-0">Favorites ({{ favourite_items.count }} Items)</h5>
                </div>
                <div class="col-md-auto">
                    <a class="btn btn-sm btn-outline-secondary border-300 me-2" href="{% url 'product_list_page' %}">
                        <span class="fas fa-chevron-left me-1" data-fa-transform="shrink-4"></span>Continue Shopping
                    </a>
                    <a class="btn btn-sm btn-primary" href="{% url 'checkout_page' %}">Checkout</a>
                </div>
            </div>
        </div>
        <div class="card-body p-0">
            <div class="row gx-card mx-0 bg-200 text-900 fs--1 fw-semi-bold">
                <div class="col-9 col-md-8 py-2">Image</div>
                <div class="col-3 col-md-4">
                    <div class="row">
                        <div class="col-md-4 py-2 text-center">Actions</div>
                        <div class="col-md-4 text-end py-2">Price</div>
                    </div>
                </div>
            </div>
            {% for item in favourite_items %}
                <div class="row gx-card mx-0 align-items-center border-bottom border-200">
                    <div class="col-8 py-3">
                        <div class="d-flex align-items-center">
                            <a href="{% url 'product_detail_page' item.pk %}">
                                <img class="img-fluid rounded-1 me-3 d-none d-md-block"
                                     src="{{ item.product.images.first.image.url }}"
                                     alt="{{ item.product.title }}" width="60"/>
                            </a>
                            <div class="flex-1">
                                <h5 class="fs-0">
                                    <a class="text-900" href="{% url 'product_detail_page' item.pk %}">
                                        {{ item.product.title }}
                                    </a>
                                </h5>
                                <div class="fs--2 fs-md--1">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4 py-3">
                        <div class="row align-items-center">
                            <div class="col-md-4 d-flex justify-content-center order-1 order-md-0">
                                <div>
                                </div>
                            </div>
                            <div class="col-md-4 d-flex justify-content-center order-2 order-md-1 my-2 my-md-0">
                                <button type="button" class="btn btn-outline-danger btn-md"
                                        onclick="toggleFavorite({{ item.pk }})">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-heart-fill" viewBox="0 0 16 16" style="width: 1em; height: 1em;">
                                        <path fill-rule="evenodd"
                                              d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
                                    </svg>
                                    Favourite
                                </button>
                            </div>
                            <div class="col-md-4 text-end ps-0 order-0 order-md-2 text-600">
                                ${{ item.product.new_price }}</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="row fw-bold gx-card mx-0">
                <div class="col px-0"></div>
                <div class="row gx-card mx-0">
            </div>
            </div>
        </div>
        <div class="card-footer bg-light d-flex justify-content-end">
            <form class="me-3">
            </form>
            <a class="btn btn-sm btn-primary" href="{% url 'checkout_page' %}">Checkout</a>
        </div>
    </div>
{% endblock %}