apps/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import ProductListView, ProductDetailTemplateView, RegisterCreateView, \
    SettingsUpdateView, FavouriteView, CartListView, CartItemDeleteView, AddToCartView, CustomLogoutView, \
    CheckoutListView, \
    AddressCreateView, AddressUpdateView, OrderCreateView, OrderListView, OrderDetailView, OrderDeleteView, \
    OrderPdfCreateView

urlpatterns = [
    # path('rv/', ProductLIstTemplateView.as_view(), name='product_list'),
    path('', ProductListView.as_view(), name='product_list_page'),
    path('product-detail/<int:pk>/', ProductDetailTemplateView.as_view(), name='product_detail'),

    path('settings', SettingsUpdateView.as_view(), name='settings_page'),
    path('register', RegisterCreateView.as_view(), name='register_page'),

    path('login', LoginView.as_view(
        template_name='apps/auth/login.html',
        redirect_authenticated_user=True
    ), name='login_page'),
    path('logout', CustomLogoutView.as_view(template_name='apps/auth/login.html'), name='logout_page'),

    path('shopping-cart', CartListView.as_view(), name='shopping_cart_page'),
    path('remove-cart/<int:pk>/', CartItemDeleteView.as_view(), name='delete_cart_item'),
    path('add-to-cart/<int:pk>/', AddToCartView.as_view(), name='add_cart_page'),

    path('favorite/<int:pk>', FavouriteView.as_view(), name='add_favorite'),

    path('checkout', CheckoutListView.as_view(), name='checkout_page'),

    path('addres-create', AddressCreateView.as_view(), name='create_address'),
    path('address-update/<int:pk>/', AddressUpdateView.as_view(), name='update_address'),

    path('orders', OrderListView.as_view(), name='orders_list'),
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order'),
    path('order/delete/<int:pk>', OrderDeleteView.as_view(), name='order_delete'),
    path('download-pdf/<int:pk>', OrderPdfCreateView.as_view(), name='download_pdf'),


]

root/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from root.settings import MEDIA_URL, MEDIA_ROOT, STATIC_URL, STATIC_ROOT

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include('apps.urls')),
                  path("ckeditor5/", include('django_ckeditor_5.urls')),
                  path('accounts/', include('allauth.urls')),
              ] + debug_toolbar_urls() + static(MEDIA_URL, document_root=MEDIA_ROOT) + static(STATIC_URL,
                                                                                              document_root=STATIC_ROOT)

apps/models.py
from datetime import timedelta
from decimal import Decimal

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser
from django.db.models import Model, JSONField, TextChoices, DateField, CharField, CASCADE, \
    PositiveIntegerField, ForeignKey, DateTimeField, TextField, EmailField, SlugField, ManyToManyField, DecimalField, \
    ImageField, BooleanField, Sum, F, FileField
from django.utils.text import slugify
from django.utils.timezone import now
from django_ckeditor_5.fields import CKEditor5Field
from mptt.models import MPTTModel, TreeForeignKey


# class CreatedBaseModel(Model):
#     updated_at = DateTimeField(auto_now=True)
#     created_at = DateTimeField(auto_now_add=True)
#
#     class Meta:
#         abstract = True


class User(AbstractUser):
    has_premium = BooleanField(default=False)

    @property
    def cart_count(self):
        return self.cart_items.count()


class Category(MPTTModel):
    name = CharField(max_length=255, unique=True)
    slug = SlugField(max_length=255, unique=True, editable=False)
    parent = TreeForeignKey('self', on_delete=CASCADE, null=True, blank=True, related_name='children')

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.slug:
            self.slug = slugify(self.name)
            unique = self.slug
            num = 1
            while Category.objects.filter(slug=unique).exists(): # todo Category orniga self qilib qoysak ozini olib ketadi
                unique = f'{self.slug}-{num}'
                num += 1
            self.slug = unique
        super().save(force_insert, force_update, using, update_fields)

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return self.name


class Product(Model):
    title = CharField(max_length=355)
    price = DecimalField(max_digits=7, decimal_places=2)
    price_percentage = DecimalField(max_digits=5, decimal_places=2, default=0)
    shopping_cost = DecimalField(default=0, max_digits=7, decimal_places=2)
    quantity = PositiveIntegerField(default=0)
    description = JSONField()
    short_description = CKEditor5Field()
    long_description = CKEditor5Field()
    category = ForeignKey('apps.Category', CASCADE)
    tags = ManyToManyField('apps.Tag', related_name='tag')
    updated_at = DateTimeField(auto_now_add=True)
    created_at = DateTimeField(auto_now_add=True)
    is_premium = BooleanField(default=False)

    def __str__(self):
        return self.title

    @property
    def new_price(self):
        return self.price * (100 - self.price_percentage) // 100

    @property
    def is_new(self) -> bool:
        return self.created_at >= now() - timedelta(days=7)

    @property
    def sub_amount(self):
        return self.price * self.quantity


class ImageProduct(Model):
    image = ImageField(upload_to='products/%Y/%m/%d/')
    product = ForeignKey('apps.Product', CASCADE, related_name='images')


class Tag(Model):
    name = CharField(max_length=255)
    slug = SlugField(max_length=255, unique=True, editable=False)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.slug:
            self.slug = slugify(self.name)
            unique = self.slug
            num = 1
            while Tag.objects.filter(slug=unique).exists():
                unique = f'{self.slug}-{num}'
                num += 1
            self.slug = unique
        super().save(force_insert, force_update, using, update_fields)


class Review(Model):
    name = CharField(max_length=255)
    email = EmailField(max_length=255, null=True, blank=True)
    description = TextField()
    comment_status = TextField()
    created_at = DateTimeField(auto_now_add=True)
    product = ForeignKey('apps.Product', CASCADE, related_name='reviw')

    def __str__(self):
        return self.name


class Favorite(Model):
    user = ForeignKey(User, CASCADE)
    product = ForeignKey('apps.Product', CASCADE)
    created_at = DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'product')


class CartItem(Model):
    product = ForeignKey('apps.Product', CASCADE)
    user = ForeignKey('apps.User', CASCADE, related_name='cart_items')
    quantity = PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.title}"

    @property
    def amount(self):
        return self.quantity * self.product.new_price

    @property
    def total(self):
        return self.amount - self.product.shopping_cost


class Order(Model):
    class StatusMethod(TextChoices):
        COMPLETED = 'completed', 'Completed'
        PROCESSING = 'processing', 'Processing'
        ON_HOLD = 'on hold', 'On Hold'
        PENDING = 'pending', 'Pending'

    class PaymentMethod(TextChoices):
        PAYPAL = 'paypal', 'Paypal'
        CREDIT_CARD = 'credit_card', 'Credit_card'

    status = CharField(max_length=255, choices=StatusMethod)
    payment_method = CharField(max_length=255, choices=PaymentMethod)
    address = ForeignKey('apps.Address', CASCADE)
    owner = ForeignKey('apps.User', CASCADE, related_name='orders')
    created_at = DateTimeField(auto_now_add=True)
    pdf_file = FileField(upload_to='order/pdf/', null=True, blank=True)

    def __str__(self):
        return f'Order {self.id} - {self.status}'

    @property
    def amount(self):
        aggregated = self.order_items.aggregate(
            subtotal=Sum(
                (F('quantity') * (F('product__price') * (100 - F('product__price_percentage')) / 100)) + F(
                    'product__shopping_cost')
            )
        )

        subtotal = aggregated['subtotal'] or Decimal('0')
        tax = subtotal * Decimal('0.10')
        total = subtotal + tax

        return {
            'subtotal': subtotal,
            'tax': tax,
            'total': total
        }


class OrderItem(Model):
    product = ForeignKey('apps.Product', CASCADE)
    order = ForeignKey('apps.Order', CASCADE, related_name='order_items')
    quantity = PositiveIntegerField(default=0)

    @property
    def sub_amount(self):
        return self.quantity * self.product.new_price


class Address(Model):
    user = ForeignKey('apps.User', CASCADE)
    full_name = CharField(max_length=255)
    street = CharField(max_length=255)
    zip_code = PositiveIntegerField()
    city = CharField(max_length=255)
    phone = CharField(max_length=255)


class CreditCard(Model):
    order = ForeignKey('apps.Order', CASCADE)
    number = CharField(max_length=255)
    cvv = CharField(max_length=255)
    expire_date = DateField()
    owner = ForeignKey('apps.User', CASCADE)


class SiteSettings(Model):
    tax = PositiveIntegerField()

    # @property
    # def sub_tax(self):
    #     return

    # TODO opshiy summadan tax di ovolish kerak nechi foiz bolsa foizda qilib
    # TODO pdf file di order ichiga saqlash kerak boladi pdf_field = order.pdf

templates/apps/order/order-detail.html
{% extends 'apps/base.html' %}

{% load static %}
{% load humanize %}
{% load tz %}
{% load custom_tags %}

{% block content %}

    <div class="card mb-3">
        <div class="bg-holder d-none d-lg-block bg-card"
             style="background-image:url({% static 'apps/assets/img/icons/spot-illustrations/corner-4.png' %});opacity: 0.7;">
        </div>
    
        <div class="card-body position-relative">
            <h5>Order Details: #{{ order.pk }}</h5>
            <p class="fs--1">{{ order.created_at|date:"F j, Y, g:i A" }}</p>
            <div><strong class="me-2">Status: </strong>
                {% if order.status == 'Completed' %}
                    <div
                            class="badge rounded-pill badge-soft-success fs--2">Completed<span
                            class="ms-1 fas fa-check" data-fa-transform="shrink-2"></span></div>
                {% elif order.status == 'Processing' %}
                    <div
                            class="badge rounded-pill badge-soft-primary fs--2">Processing<span
                            class="ms-1 fas fa-redo"
                            data-fa-transform="shrink-2"></span></div>

                {% elif order.status == 'On Hold' %}
                    <div
                            class="badge rounded-pill badge-soft-secondary fs--2">On Hold<span
                            class="ms-1 fas fa-ban"
                            data-fa-transform="shrink-2"></span></div>

                {% else %}
                    <div
                            class="badge rounded-pill badge-soft-warning fs--2">Pending<span
                            class="ms-1 fas fa-stream"
                            data-fa-transform="shrink-2"></span></div>

                {% endif %}
            </div>
        </div>
    </div>



    <div class="card mb-3">
        <div class="card-body">
            <div class="row">
                <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
                    <h5 class="mb-3 fs-0">Shipping Address</h5>
                    <h6 class="mb-2">{{ order.address.full_name }}</h6>
                    <p class="mb-0 fs--1">{{ order.address.city }},
                        <br/>{{ order.address.street }}, {{ order.address.zip_code }}</p>
                    <div class="text-500 fs--1">(Free Shipping)</div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <h5 class="mb-3 fs-0">Payment Method</h5>
                    <div class="d-flex">
                        <img class="me-3" src="{% static 'apps/assets/img/icons/visa.png' %}" width="40" height="30"
                             alt=""/>
                        <div class="flex-1">
                            <h6 class="mb-0">{{ order.address.full_name }}</h6>
                            <p class="mb-0 fs--1">{{ order.creditcard_set.number }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-auto">
                    <a href="{% url 'download_pdf' order.pk %}" target="_blank">
                        <button class="btn btn-falcon-default btn-sm me-1 mb-2 mb-sm-0" type="button">
                            <svg class="svg-inline--fa fa-arrow-down fa-w-14 me-1" aria-hidden="true" focusable="false"
                                 data-prefix="fas" data-icon="arrow-down" role="img" xmlns="http://www.w3.org/2000/svg"
                                 viewBox="0 0 448 512" data-fa-i2svg="">
                                <path fill="currentColor"
                                      d="M413.1 222.5l22.2 22.2c9.4 9.4 9.4 24.6 0 33.9L241 473c-9.4 9.4-24.6 9.4-33.9 0L12.7 278.6c-9.4-9.4-9.4-24.6 0-33.9l22.2-22.2c9.5-9.5 25-9.3 34.3.4L184 343.4V56c0-13.3 10.7-24 24-24h32c13.3 0 24 10.7 24 24v287.4l114.8-120.5c9.3-9.8 24.8-10 34.3-.4z"></path>
                            </svg>
                            Download (.pdf)
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="card mb-3">
        <div class="card-body">
            <div class="table-responsive fs--1">
                <table class="table table-striped border-bottom">
                    <thead class="bg-200 text-900">
                    <tr>
                        <th class="border-0">Products</th>
                        <th class="border-0 text-center">Quantity</th>
                        <th class="border-0 text-end">Rate</th>
                        <th class="border-0 text-end">Amount</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order_item in order.order_items.all %}
                        <tr class="border-200">
                            <td class="align-middle">
                                <h6 class="mb-0 text-nowrap">{{ order_item.product.title }}</h6>
                                <p class="mb-0">{{ order_item.product.short_description|safe }}</p>
                            </td>
                            <td class="align-middle text-center">{{ order_item.quantity }}</td>
                            <td class="align-middle text-end">${{ order_item.product.new_price }}</td>
                            <td class="align-middle text-end">${{ order_item.sub_amount }}</td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
            <div class="row g-0 justify-content-end">
                <div class="col-auto">
                    <table class="table table-sm table-borderless fs--1 text-end">
                        <tr>
                            <th class="text-900">Subtotal:</th>
                            <td class="fw-semi-bold">${{ order.amount.subtotal }}</td>
                        </tr>
                        <tr>
                            <th class="text-900">Tax 5%:</th>
                            <td class="fw-semi-bold">${{ order.amount.tax }}</td>
                        </tr>
                        <tr class="border-top">
                            <th class="text-900">Total:</th>
                            <td class="fw-semi-bold">${{ order.amount.total }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/apps/order/order-list.html
{% extends 'apps/base.html' %}

{% block content %}
    <div class="card mb-3" id="ordersTable"
         data-list='{"valueNames":["order","date","address","status","amount"],"page":10,"pagination":true}'>
        <div class="card-header">
            <div class="row flex-between-center">
                <div class="col-4 col-sm-auto d-flex align-items-center pe-0">
                    <h5 class="fs-0 mb-0 text-nowrap py-2 py-xl-0">Orders</h5>
                </div>
                <div class="col-8 col-sm-auto ms-auto text-end ps-0">
                    <div class="d-none" id="orders-bulk-actions">
                        <div class="d-flex">
                            <select class="form-select form-select-sm" aria-label="Bulk actions">
                                <option selected="">Bulk actions</option>
                                <option value="Refund">Refund</option>
                                <option value="Delete">Delete</option>
                                <option value="Archive">Archive</option>
                            </select>
                            <button class="btn btn-falcon-default btn-sm ms-2" type="button">Apply</button>
                        </div>
                    </div>
                    <div id="orders-actions">
                        <button class="btn btn-falcon-default btn-sm" type="button"><span class="fas fa-plus"
                                                                                          data-fa-transform="shrink-3 down-2"></span><span
                                class="d-none d-sm-inline-block ms-1">New</span></button>
                        <button class="btn btn-falcon-default btn-sm mx-2" type="button"><span class="fas fa-filter"
                                                                                               data-fa-transform="shrink-3 down-2"></span><span
                                class="d-none d-sm-inline-block ms-1">Filter</span></button>
                        <button class="btn btn-falcon-default btn-sm" type="button"><span
                                class="fas fa-external-link-alt" data-fa-transform="shrink-3 down-2"></span><span
                                class="d-none d-sm-inline-block ms-1">Export</span></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive scrollbar">
                <table class="table table-sm table-striped fs--1 mb-0 overflow-hidden">
                    <thead class="bg-200 text-900">
                    <tr>
                        <th>
                            <div class="form-check fs-0 mb-0 d-flex align-items-center">
                                <input class="form-check-input" id="checkbox-bulk-customers-select" type="checkbox"
                                       data-bulk-select='{"body":"table-orders-body","actions":"orders-bulk-actions","replacedElement":"orders-actions"}'/>
                            </div>
                        </th>
                        <th class="sort pe-1 align-middle white-space-nowrap" data-sort="order">Order</th>
                        <th class="sort pe-1 align-middle white-space-nowrap pe-7" data-sort="date">Date</th>
                        <th class="sort pe-1 align-middle white-space-nowrap" data-sort="address"
                            style="min-width: 12.5rem;">Ship To
                        </th>
                        <th class="sort pe-1 align-middle white-space-nowrap text-center" data-sort="status">Status</th>
                        <th class="sort pe-1 align-middle white-space-nowrap text-end" data-sort="amount">Amount</th>
                        <th class="no-sort"></th>
                    </tr>
                    </thead>
                    <tbody class="list" id="table-orders-body">
                    {% for order in orders %}
                        <tr class="btn-reveal-trigger">
                            <td class="align-middle" style="width: 28px;">
                                <div class="form-check fs-0 mb-0 d-flex align-items-center">
                                    <input class="form-check-input" type="checkbox" id="checkbox-0"
                                           data-bulk-select-row="data-bulk-select-row"/>
                                </div>
                            </td>
                            <td class="order py-2 align-middle white-space-nowrap"><a
                                    href="{% url 'order' order.pk %}">
                                {% if user.is_superuser or user.is_staff %}
                                    <strong>#{{ order.pk }}</strong></a>
                                    by {{ order.address.full_name }}
                                {% endif %}
                                <strong>{{ order.owner.get_full_name }}</strong><br/><a
                                        href="mailto:{{ order.owner.email }}">{{ order.owner.email }}</a>
                            </td>
                            <td class="date py-2 align-middle">{{ order.created_at|date:"d/m/Y" }}</td>
                            <td class="address py-2 align-middle white-space-nowrap">{{ order.address.full_name }}, {{ order.address.city }}
                                <p class="mb-0 text-500"> {{ order.address.street }}, {{ order.address.zip_code }}</p>
                            </td>
                            {% if order.status == 'Completed' %}
                                <td class="status py-2 align-middle text-center fs-0 white-space-nowrap"><span
                                        class="badge badge rounded-pill d-block badge-soft-success">Completed<span
                                        class="ms-1 fas fa-check" data-fa-transform="shrink-2"></span></span>
                                </td>
                            {% elif order.status == 'Processing' %}
                                <td class="status py-2 align-middle text-center fs-0 white-space-nowrap"><span
                                        class="badge badge rounded-pill d-block badge-soft-primary">Processing<span
                                        class="ms-1 fas fa-redo"
                                        data-fa-transform="shrink-2"></span></span>
                                </td>
                            {% elif order.status == 'On Hold' %}
                                <td class="status py-2 align-middle text-center fs-0 white-space-nowrap"><span
                                        class="badge badge rounded-pill d-block badge-soft-secondary">On Hold<span
                                        class="ms-1 fas fa-ban"
                                        data-fa-transform="shrink-2"></span></span>
                                </td>
                            {% else %}
                                <td class="status py-2 align-middle text-center fs-0 white-space-nowrap"><span
                                        class="badge badge rounded-pill d-block badge-soft-warning">Pending<span
                                        class="ms-1 fas fa-stream"
                                        data-fa-transform="shrink-2"></span></span>
                                </td>
                            {% endif %}
                            <td class="amount py-2 align-middle text-end fs-0 fw-medium">${{ order.amount.total }}</td>
                            <td class="py-2 align-middle white-space-nowrap text-end">
                                <div class="dropdown font-sans-serif position-static">
{#                                    <button class="btn btn-link text-600 btn-sm dropdown-toggle btn-reveal"#}
{#                                            type="button"#}
{#                                            id="order-dropdown-0" data-bs-toggle="dropdown" data-boundary="viewport"#}
{#                                            aria-haspopup="true" aria-expanded="false"><span#}
{#                                            class="fas fa-ellipsis-h fs--1"></span></button>#}
                                    <div class="dropdown-menu dropdown-menu-end border py-0"
                                         aria-labelledby="order-dropdown-0">
                                        <div class="bg-white py-2"><a class="dropdown-item" href="#!">Completed</a><a
                                                class="dropdown-item" href="#!">Processing</a><a class="dropdown-item"
                                                                                                 href="#!">On Hold</a><a
                                                class="dropdown-item" href="#!">Pending</a>
                                            <div class="dropdown-divider"></div>
                                            <form action="{% url 'order_delete' order.pk %}" method="post">
                                                {% csrf_token %}
                                                <button class="dropdown-item text-danger">
                                                    Delete
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            {% include 'apps/parts/_pagination.html' %}
        </div>
    </div>
{% endblock %}